name: Install Scrypted
description: Install Scrypted service on GitHub Actions
author: Brett Jia

inputs:
  version:
    description: Scrypted server version
    required: true
    default: latest
  repo:
    description: Source GitHub repo to pull install scripts from
    required: true
    default: koush/scrypted
  branch:
    description: Source GitHub branch to pull install scripts from
    required: true
    default: main
  healthcheck:
    description: Verify Scrypted server is up and running at port 10443
    required: true
    type: bool
    default: true

runs:
  using: composite

  steps:
    - name: Run install script
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/${{ inputs.repo }}/${{ inputs.branch }}/install/local/install-scrypted-dependencies-linux.sh | sudo SERVICE_USER=$USER SCRYPTED_INSTALL_VERSION=${{ inputs.version }} bash

    - name: Run install script
      if: runner.os == 'macOS'
      shell: bash
      run: |
        export SCRYPTED_INSTALL_VERSION='${{ inputs.version }}'
        mkdir -p ~/.scrypted
        curl -s https://raw.githubusercontent.com/${{ inputs.repo }}/${{ inputs.branch }}/install/local/install-scrypted-dependencies-mac.sh > ~/.scrypted/install-scrypted-dependencies-mac.sh
        bash ~/.scrypted/install-scrypted-dependencies-mac.sh

    - name: Run install script
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        [Environment]::SetEnvironmentVariable('SCRYPTED_INSTALL_VERSION','${{ inputs.version }}', 'User')
        iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/${{ inputs.repo }}/${{ inputs.branch }}/install/local/install-scrypted-dependencies-win.ps1'))

    - name: Wait for server to start
      if: ${{ inputs.healthcheck }}
      shell: bash
      run: |
        curl -k --retry 20 --retry-all-errors --retry-max-time 600 https://localhost:10443/
 
